title: The Old Time Wasters
description: Rip-roaring, foot-stomping, knee-slapping, rib-tickling Old Time music (with an English accent)
sitename: The Old Time Wasters
sass:
  sass_dir: /assets/_sass
  sourcemap: true
  style: :compressed
collections:
  - gigs
  - features
  - videos
  - members
  - recordings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
assets:
  source_maps: true
